# Basic config
set -g default-terminal "tmux-256color"
set -g mouse on

#Key bindings
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -hc "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Status bar
# set -g status-fg black
# set -g status-bg brightblue
# set -g status-fg black
# set -g status-bg colour69

# Status bar theme
set -g pane-active-border-style fg=colour13
set -g pane-border-style fg=colour239

set -g message-style fg=colour0
set -g message-style bg=colour13

set -g status-justify left
set -g status-bg "colour236"
set -g status-fg white

setw -g clock-mode-colour "colour13"

#setw -g status-left-style fg=bold
setw -g status-left-style fg=black,bold
setw -g status-left-style bg=colour13

set -g status-right-length "100"
set -g status-right "#[bg=colour239] %a %B %-d, %Y #[fg=colour13].:. #[fg=white]%H:%M #[fg=black,bg=colour13]#[bold] #h "

#setw -g window-status-bell-fg red
#setw -g window-status-activity-fg yellow

set -g window-status-activity-style 'bg=yellow,fg=colour0'
set -g window-status-bell-style 'bg=red,fg=colour15'
set -g monitor-activity on

setw -g window-status-format " #I: #W "
setw -g window-status-separator ""
setw -g window-status-style fg=colour13

setw -g window-status-current-format " #I: #W "
setw -g window-status-current-style fg=colour15
setw -g window-status-current-style bg=colour239
# End theme

# List of plugins
# set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin "arcticicestudio/nord-tmux"

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
